version: "3.9"

services:
  angular: 
    build: news-site
    ports: 
      - 80:80
      
  api:
    build: ./news-api
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"

