version: "3.9"

services:
  api:
    build: ./news-api
    command: python manage.py runserver 0.0.0.0:8000
#    command: gunicorn news_project.wsgi:application --bind 0.0.0.0:443
    #RUN gunicorn  --certfile=/etc/certs/localhost.crt --keyfile=/etc/certs/localhost.key news_project.wsgi:application --bind 0.0.0.0:443
    expose:
      - 8000

  nginx:
    build:
      dockerfile: ./nginx/Dockerfile
      context: ./
    ports:
      - 443:443
      - 80:80
    restart: "on-failure"

