version: "3.9"

services:
  api:
    build:
      dockerfile: ./news-api/Dockerfile
      context: ./
    command: python manage.py runserver 0.0.0.0:8000
    expose:
      - 8000


  nginx:
    build:
      dockerfile: ./nginx/Dockerfile
      context: ./
    ports:
      - 443:443
      - 80:80
    restart: "on-failure"
