# Generated by Django 3.2.11 on 2022-01-19 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_site', models.CharField(db_index=True, max_length=40)),
                ('link', models.CharField(db_index=True, max_length=500, null=True)),
                ('title', models.CharField(max_length=100, null=True)),
                ('summary', models.CharField(max_length=500, null=True)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('click_count', models.IntegerField()),
            ],
        ),
    ]
