# Generated by Django 3.2.11 on 2022-01-20 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='base_site',
            new_name='site_name',
        ),
    ]
